### ISSUE TITLE
node red xeoma flow

### ISSUE THREAD

**Issue by tarbax** [skylord123/xeoma-mqtt#2]
cant get the xeoma to send messages to node red.

what aim i doing wrong?

resulting url:
http://username:password@192.168.1.140:1880/xeoma_to_mqtt?channel=tuinhuis&msg=%3Cmsg-payload%3E

**Comment by skylord123** [comment]
I would try and attach debug nodes and seeing how far into the chain if at all it's getting. 

When you go to that URL in your browser does it send the message or reach your debugs? (if you add more than one debug you can click the node ID in the console to jump to exactly which one the message came from which will help you see how far into the chain it got)

**Comment by skylord123** [comment]
@tarbax any luck? Did you get your issue resolved?

**Comment by tarbax** [comment]
> @tarbax any luck? Did you get your issue resolved?

Once i try the link in browser i get a login screen and it refuses my username and pass
but i can login into node red with the same credentials.

And the test in xeoma verifies that everything is correct but i don't get any debug messages in node red.

**Comment by skylord123** [comment]
I don't use authentication but it sounds like you may need to configure node-red differently.

Go down to the bottom of this page where it says "HTTP Node Security": https://nodered.org/docs/security#http-node-security

If you enabled authentication there is another setting for setting up authentication for HTTP nodes (which is what the flow I created uses). Try setting the `httpNodeAuth` in your `settings.js` file (according to the link above) and authenticating with those credentials.

It seems the node-red authentication isn't shared between node-red and the HTTP nodes which requires you to create a username/password for both individually. I guess this makes sense if you want something to be able to send data in but without being able to edit the node-red flows.

@tarbax let me know if this works for you. If not I will setup a test env and check it out.

**Comment by tarbax** [comment]
> I don't use authentication but it sounds like you may need to configure node-red differently.
> 
> Go down to the bottom of this page where it says "HTTP Node Security": https://nodered.org/docs/security#http-node-security
> 
> If you enabled authentication there is another setting for setting up authentication for HTTP nodes (which is what the flow I created uses). Try setting the `httpNodeAuth` in your `settings.js` file (according to the link above) and authenticating with those credentials.
> 
> It seems the node-red authentication isn't shared between node-red and the HTTP nodes which requires you to create a username/password for both individually. I guess this makes sense if you want something to be able to send data in but without being able to edit the node-red flows.
> 
> @tarbax let me know if this works for you. If not I will setup a test env and check it out.

i am using node-red addon on hassio (home assistant) so it takes the login credentials of home assistant users to node-red.

**Comment by tarbax** [comment]
I reinstalled and problem was solved.
Had a bad install.

**Comment by skylord123** [comment]
@tarbax glad you got it resolved. Let me know if you have any issues moving forward.

Thanks.

**Comment by tarbax** [comment]
@skylord123 
Actually the link is working in my browser but not the HTTP Node in xeoma.
Are any of my setting wrong? if i test is says sucsesfull but i don't see anything in node red.

![image](https://user-images.githubusercontent.com/34491557/54074026-06e57100-428e-11e9-837a-83761d5013ec.png)

**Comment by skylord123** [comment]
@tarbax Instead of placing the arguments inside the `Host name or IP address` field click the `Show all parameters` checkbox and set it up something like this:

![image](https://user-images.githubusercontent.com/3412313/54586634-45440400-49e3-11e9-82dd-e06a294fd874.png)

Also the `Send` dropdown lets you select what should trigger the HTTP request. Because of this I create two HTTP Request Senders and just change the message for when the motion starts to `1` or `true` and then the other to send a `0` or `false` when the motion stops.

![image](https://user-images.githubusercontent.com/3412313/54586786-b683b700-49e3-11e9-8274-d60be5d0f394.png)

Anyways, I think your problem is just where you defined your arguments.

**Comment by skylord123** [comment]
If you do setup two HTTP Request senders like I did and have issues with the end event not always sending let me know. I have a fix for it. This is a bug I ran into but I think the devs have fixed it.
